const navToggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.nav');navToggle?.addEventListener('click',()=>{const o=nav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(o))});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const dayTabs=[...document.querySelectorAll('.day-tab')],dayPanels=[...document.querySelectorAll('.day-panel')];dayTabs.forEach(tab=>tab.addEventListener('click',()=>{dayTabs.forEach(t=>t.classList.remove('active'));dayPanels.forEach(p=>p.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.day)?.classList.add('active')}));
const statusEl=document.getElementById('trip-status'),local=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Taipei'})),ymd=`${local.getFullYear()}-${String(local.getMonth()+1).padStart(2,'0')}-${String(local.getDate()).padStart(2,'0')}`;if(ymd<'2026-09-23')statusEl.textContent='倒數出發，曼谷見。';else if(ymd<='2026-09-28')statusEl.textContent='旅途中。今天也慢慢看、慢慢走。';else statusEl.textContent='旅程結束，但這本旅遊書還留著。';
const spots=[
{band:'王城必看',name:'1. 大皇宮＋玉佛寺',en:'Grand Palace & Wat Phra Kaew',lead:'這裡不是單純的「漂亮寺廟」：它是曼谷建都後，王室、國家儀式與信仰被放在一起的核心。',story:'1782 年，拉瑪一世把首都移到昭披耶河東岸並興建大皇宮。宮牆內的玉佛寺是皇家佛寺，沒有僧侶常住；最重要的主角是約 66 公分高、以綠色碧玉雕成的玉佛。',more:'玉佛早在曼谷建都前就歷經多地輾轉，最後被迎入皇家佛寺，因此不只是一尊佛像，也象徵王朝正統與國家守護。',look:['玉佛本尊其實比想像中小，位置很高，重點是地位極高。','玉佛一年會依熱季、雨季、涼季更換 3 套金製衣飾。','看傳統泰式屋頂、金色尖塔與歐洲風格宮殿立面同框。'],talk:'「這裡可以想成泰國版的皇宮＋國家級佛寺。玉佛不大，但地位超級高，而且一年還會換三套衣服。」'},
{band:'寺廟＋泰式按摩',name:'2. 臥佛寺',en:'Wat Pho｜Wat Phra Chetuphon',lead:'大家先看到「超大臥佛」，但真正有趣的是：這座寺也像一間古代知識博物館，是泰式按摩的重要傳承地。',story:'臥佛寺位於大皇宮旁。拉瑪三世時期，寺中大量刻石與圖解用來保存醫學、按摩、文學與生活知識，因此常被形容成泰國早期的公共教育中心。',more:'19 世紀時，各種知識被刻在石碑與圖像上，讓一般人也能學習；今天看到的按摩線圖，就是當年的知識保存方式。',look:['臥佛最值得看的是腳底的精細圖案與佛教宇宙觀象徵。','不要只看臥佛殿，外面的彩瓷佛塔群也很漂亮。','牆面可找到與傳統醫學、按摩姿勢相關的圖示。'],talk:'「這裡厲害的不只是佛很大。以前很多醫學、按摩、文學知識都被刻在寺裡，像古代版的公開知識庫。」'},
{band:'河岸夕陽',name:'3. Wat Pho Pier 看夕陽',en:'Tha Tien / Wat Pho riverside',lead:'這一站的主角其實在河對岸：站在臥佛寺這側，看夕陽把鄭王廟變成曼谷最經典的剪影。',story:'昭披耶河把曼谷舊城與吞武里分開。鄭王廟位在西岸，從 Tha Tien 一側往西看，傍晚能把主塔、河面、船隻與落日放進同一個畫面。',more:'道路普及以前，皇宮、寺廟、市場與居民生活都大量依賴水路。這裡同時看見東岸的拉達那哥欣王城與西岸較早的吞武里記憶。',look:['夕陽前，白色瓷片與塔身會慢慢變暖。','日落瞬間，用河上船隻當前景拍主塔剪影。','日落後別急著走，等天空變深藍、鄭王廟亮燈。'],talk:'「鄭王廟雖然叫黎明寺，可是我們站的這一岸，反而是看它夕陽最經典的位置。」'},
{band:'華人老城',name:'4. 中國城',en:'Yaowarat｜เยาวราช',lead:'白天像批發商圈，晚上像整條街一起開火：中國城是曼谷最有「聲音、香味、霓虹」的區域之一。',story:'Yaowarat 一帶聚集金行、藥材、乾貨、廟宇與餐飲；白天是做生意的老商圈，入夜後街邊攤與招牌燈光讓整個街區完全換一張臉。',more:'1782 年曼谷建都時，原本住在王城附近的華人社群往南遷，之後在三聘、耀華力一帶逐漸形成大型商業區。',look:['看大量紅金色的金行招牌。','主幹道之外更要往小巷裡走，看老店與生活感。','晚上留胃給海鮮、粿條、甜品與燒烤。'],talk:'「這裡白天跟晚上完全兩種城市。白天是老商圈，晚上才像把所有招牌、攤販和食物一次打開。」'},
{band:'寺廟＋華人史',name:'5. 金佛寺',en:'Wat Traimit',lead:'這尊佛最戲劇化的地方不是「鍍金」，而是它真的由大量黃金打造，而且曾被外層灰泥掩藏很久。',story:'金佛寺位於中國城入口附近，最知名的是素可泰風格黃金佛像。搬運時外層覆蓋物破裂，才讓人重新發現裡面其實是金質佛像。',more:'佛像何時被覆上灰泥沒有完全確定的紀錄；常見說法認為可能為了在戰亂年代隱藏真正材質，直到 20 世紀搬遷時才重新露出。',look:['看佛像柔和的素可泰風格，不只是看「金」。','很適合作為中國城散步的起點。','把寺廟和附近華人街區歷史一起看，會比單獨打卡更有意思。'],talk:'「它最酷的是以前外面被灰泥包著，直到搬運時裂開，大家才發現裡面竟然是真金佛像。」'},
{band:'老城新潮',name:'6. Song Wat Road',en:'ทรงวาด｜松瓦路',lead:'這條路像是「百年前的貿易街，被新一代咖啡、設計與街頭藝術重新打開」。',story:'1906 年一場大火後，拉瑪五世時期為疏通與擴展商業區而形成這條道路。靠近昭披耶河，使它曾是重要的進出口與倉儲地帶。',more:'早年的商人從河邊卸下米、香料、乾貨與進口商品，再送進中國城各條街巷，所以今天仍能看到大量倉庫與商號尺度。',look:['先看老建築與舊商號，再看新店。','注意街頭藝術如何直接嵌進老街景。','別只追咖啡店，乾貨行、麵店與五金老店才是底色。'],talk:'「這條路以前是做進出口和倉儲的，現在咖啡店、設計店跑進來，所以會看到百年老店旁邊突然冒出超潮的新店。」'},
{band:'街頭藝術＋老社區',name:'7. Talat Noi Road',en:'ตลาดน้อย｜小市場老街區',lead:'如果 Song Wat 是「老商業街變潮」，Talat Noi 更像真正有人生活、修車、拜拜，再長出街頭藝術的巷弄迷宮。',story:'Talat Noi 是曼谷很老的華人河岸社區之一，歷史超過兩百年；過去與港口、商業、金屬加工和機械零件產業關係密切。',more:'巷子裡堆疊的引擎、齒輪和舊零件不是刻意營造的復古裝飾，而是社區真實產業歷史。',look:['老車零件與機械店，就是這區的產業記憶。','巷弄裡常突然出現華人宗教空間與老宅。','街頭藝術多藏在轉角、鐵門與老牆上。'],talk:'「這區不是專門做給觀光客看的，它本來就有修車、零件、老宅和廟，後來藝術家又把作品放進來。」'},
{band:'早上市場',name:'8. 丹嫩莎朵水上市場',en:'Damnoen Saduak Floating Market',lead:'這是你腦中「泰國水上市場」最經典的畫面：窄運河、長尾船、水果與食物從船上直接交易。',story:'中部泰國過去大量依賴河流與運河交通，市場自然也沿水而生。丹嫩莎朵今天觀光化程度高，但早一點到仍能感受船隻密集穿梭的視覺衝擊。',more:'丹嫩莎朵運河在拉瑪四世時期開鑿，用來連接重要河流流域。運河完成後，沿線居民以船作為交通與交易工具。',look:['看狹窄水道裡船隻怎麼「會車」。','買東西前先問清楚價格。','注意岸上與水上是兩套不同的市場動線。'],talk:'「重點不是買很多東西，是看以前運河怎麼像馬路一樣，連市場都長在水上。」',market:true},
{band:'火車市場',name:'9. 美功鐵道市場',en:'Maeklong Railway Market｜Talad Rom Hup',lead:'它不是「市場旁邊有鐵路」，而是市場真的長在鐵軌上：火車一來，攤販幾分鐘內收傘、讓路，再恢復營業。',story:'Talad Rom Hup 意思接近「收傘市場」。平常鐵軌兩側擺滿蔬果、海鮮、乾貨；列車進站時，攤商快速收棚，火車通過後再立刻恢復。',more:'鐵路與市場長期共用有限的城市空間，最後形成非常特殊的共存方式；火車沒有把市場趕走，市場也沒有阻斷鐵路。',look:['先找安全位置，不要為了拍照站在軌道中央。','火車靠近時，攤販收棚的速度本身就是重點。','火車通過後別急著走，市場瞬間復原也很好看。'],talk:'「現在整條鐵軌都是市場，火車來的時候大家把棚子一收，火車過了又立刻開店。」',market:true},
{band:'午後到夜晚市場',name:'10. 安帕瓦水上市場',en:'Amphawa Floating Market',lead:'丹嫩莎朵看「早晨的船」，安帕瓦看的是「傍晚河岸生活」：吃東西、散步、看店屋慢慢亮燈。',story:'安帕瓦是沿運河發展的午後型水上市場。和丹嫩莎朵相比，更適合把重點放在河岸店屋、晚餐與傍晚氣氛。',more:'隨陸路交通興起，水上市場一度衰退；後來社區以老店屋、河岸飲食與在地生活重新吸引遊客，因此更像被重新活化的河岸老城。',look:['找河邊位置吃東西，看船從腳下慢慢經過。','注意木造店屋與舊社區感，不只是水上攤販。','天色暗後燈光亮起，氣氛會比正中午更迷人。'],talk:'「如果丹嫩莎朵是早上市場，安帕瓦就是晚一點來吃東西、看河邊慢慢亮燈的版本。」',market:true},
{band:'生活感街區',name:'11. Ari Area',en:'อารีย์｜Ari',lead:'這裡沒有一個「必看地標」。Ari 好玩就好玩在：拐進一條巷子，可能遇到老麵攤、漂亮咖啡館、設計小店或很有個性的住宅。',story:'Ari 是曼谷很有生活感的住宅與餐飲街區。近年咖啡、餐廳、選物與社群空間大量出現，但舊式街邊小吃與社區感仍在。',more:'Ari 並不像整體改造成文創園區，而是新店一間一間嵌進原有巷弄生活裡；更像在看當代曼谷人怎麼過週末。',look:['不要只走大馬路，Soi（巷）才是重點。','老店與新店交錯，才是 Ari 的魅力。','留空白時間，臨時看到想進的店就是驚喜。'],talk:'「Ari 沒有一定要衝去拍的地標，我們今天就是看到哪條巷子順眼就拐進去。」'}];
const flipbook=document.getElementById('flipbook'),loadingBook=document.getElementById('loadingBook'),prevBtn=document.getElementById('prevPage'),nextBtn=document.getElementById('nextPage'),pageNow=document.getElementById('pageNow'),pageTotal=document.getElementById('pageTotal');let pageFlip;
function wrapPage(html,cls=''){const page=document.createElement('div');page.className=`page ${cls}`;const inner=document.createElement('div');inner.className='page-content';inner.innerHTML=html;page.appendChild(inner);return page}
function spotHtml(s,i){return `<article class="guide-page ${s.market?'market':''}"><div class="band">${s.band}</div><span class="num">STOP ${String(i+1).padStart(2,'0')}</span><h3>${s.name}</h3><div class="en">${s.en}</div><div class="lead">✨ 一句話先懂｜${s.lead}</div><h4>30 秒故事</h4><p>${s.story}</p><div class="more"><h4>📖 再多知道一點</h4><p>${s.more}</p></div><h4>到了現場，記得看這些</h4><ul>${s.look.map(x=>`<li>${x}</li>`).join('')}</ul><div class="talk">🎙️ 可以這樣講給家人聽<br>${s.talk}</div></article>`}
function buildBook(){const cover=`<div class="book-cover"><div><div class="cover-symbol">✦</div><small>MIA'S BANGKOK POCKET GUIDE · 2026</small><h3>曼谷旅途導覽小冊</h3><p>11 個景點｜簡單、好懂、可以直接講給家人聽</p></div></div>`,summary=`<article class="guide-page guide-summary"><div class="bigmark">🗺️</div><span class="num">HOW TO READ BANGKOK</span><h3>先看懂這趟旅行的 4 種曼谷</h3><div class="summary-list"><div>👑 <b>王城曼谷</b>｜大皇宮・玉佛寺・臥佛寺</div><div>🌅 <b>河岸曼谷</b>｜Wat Pho Pier</div><div>🏮 <b>華人老城</b>｜中國城・金佛寺・Song Wat・Talat Noi</div><div>🚤 <b>市場與生活街區</b>｜丹嫩莎朵・美功・安帕瓦・Ari</div></div></article>`,tips=`<article class="guide-page guide-tips"><span class="num">BONUS PAGE</span><h3>旅途中最好用的 5 個導遊小技巧</h3><ol><li>先講一句話版本，家人有興趣再補歷史。</li><li>寺廟重點放在「為什麼重要」；街區放在「以前做什麼、現在變成什麼」。</li><li>市場先看運作方式，再買東西。</li><li>Song Wat、Talat Noi、Ari 都適合故意繞進巷子。</li><li>夕陽景點至少留到日落後 15–20 分鐘。</li></ol><blockquote>從皇城的金色，到中國城的紅色，再到河岸夕陽與巷弄生活感——曼谷不是一種樣子，而是很多時代同時活在一座城市裡。</blockquote></article>`;flipbook.appendChild(wrapPage(cover,'hard'));flipbook.appendChild(wrapPage(summary));spots.forEach((s,i)=>flipbook.appendChild(wrapPage(spotHtml(s,i))));flipbook.appendChild(wrapPage(tips));pageFlip=new St.PageFlip(flipbook,{width:520,height:735,size:'stretch',minWidth:270,maxWidth:1100,minHeight:380,maxHeight:800,maxShadowOpacity:.35,showCover:true,mobileScrollSupport:false,useMouseEvents:true,swipeDistance:24,flippingTime:650,autoSize:true,drawShadow:true});pageFlip.loadFromHTML(document.querySelectorAll('#flipbook .page'));pageTotal.textContent=pageFlip.getPageCount();pageNow.textContent=1;pageFlip.on('flip',e=>pageNow.textContent=e.data+1);flipbook.classList.add('ready');loadingBook.style.display='none'}
prevBtn?.addEventListener('click',()=>pageFlip?.flipPrev());nextBtn?.addEventListener('click',()=>pageFlip?.flipNext());document.querySelectorAll('.spot-index button').forEach(btn=>btn.addEventListener('click',()=>{pageFlip?.turnToPage(Number(btn.dataset.page));document.getElementById('guidebook')?.scrollIntoView({behavior:'smooth',block:'start'})}));try{buildBook()}catch(err){console.error(err);loadingBook.innerHTML='<strong>翻頁版載入失敗，請重新整理頁面。</strong>'}